export const profile = {
  name: "Lekhraj Saini",
  title: "Research Scientest | Atmospheric Science & Radar Meteorology",
  institution: "North Eastern Space Application Center, Department of Space, Govt. of India",
  department: "Space & Atmospheric Science Division",
  location: "Umiam, Meghalaya, India",
  email: "lekhrajsaini1403@gmail.com",
  phone: "+91-8955950049",
  bio: `Researcher with expertise in polar meteorology, Arctic precipitation, and atmospheric microphysical processes. 

Experienced in operating and analyzing data from atmospheric instruments in extreme environments including the Himadri Arctic Research Station, Svalbard (2024).

Strong background in Python and MATLAB for large-scale atmospheric data analysis and scientific visualization.`,
  shortBio: "Research Scientist working on Radar Meteorlogy, Arctic precipitation and atmospheric science.",
  linkedin: "https://www.linkedin.com/in/lekhrajsaini/",
  googleScholar: "https://scholar.google.com/citations?user=BcVzI2wAAAAJ&hl=en",
  researchgate: "https://www.researchgate.net/profile/Lekhraj-Saini-2",
  github: "https://github.com/lekhrajsaini1403",
  orcid: "https://orcid.org/0009-0005-0281-4950",
  cv: "https://drive.google.com/file/d/1vqe3th-B2pYUQYwwCDokIuIb8Kwc52du/view?usp=drivesdk",
};
export const stats = [
  { number: "6+", label: "Publications & Conferences" },
  { number: "3+", label: "Major Projects" },
  { number: "5+", label: "Awards & Grants" },
  { number: "1+", label: "Field Expeditions" },
];
export const skills = [
  "Python", "MATLAB",
  "NetCDF", "GRIB", "HDF", "CSV",
  "Scientific Visualization",
  "Radar Meteorology",
  "Remote Sensing",
  "Data Analysis",
  "Linux"
];
export const researchAreas = [
  {
    id: 1,
    icon: "❄️",
    name: "Polar Meteorology",
    description: "Study of Arctic weather systems and precipitation dynamics",
  },
  {
    id: 2,
    icon: "🌧️",
    name: "Precipitation Microphysics",
    description: "Analysis of precipitation processes and atmospheric interactions",
  },
  {
    id: 3,
    icon: "📡",
    name: "Atmospheric Instrumentation",
    description: "Working with radar, radiometers, and weather sensors",
  },
  {
    id: 4,
    icon: "🛰️",
    name: "Remote Sensing",
    description: "Satellite and ground-based atmospheric observations",
  },
  {
    id: 5,
    icon: "📊",
    name: "Scientific Data Analysis",
    description: "Large-scale atmospheric data processing and visualization",
  },
];
export const publications = [
  {
    id: 1,
    title: "Case studies of different types of precipitation at Ny-Ålesund, Arctic",
    authors: "Saini, L., Das, S., Murukesh, N.",
    type: "journal",
    typeLabel: "Journal Article",
    Journal: "Scientific Reports",
    year: 2025,
    doi: "https://doi.org/10.1038/s41598-025-85833-2",
    featured: true,
  },
  {
    id: 2,
    title: "Vertical evolution of precipitation at Ny-Ålesund",
    authors: "Saini, L., Das, S., Murukesh, N.",
    type: "journal",
    typeLabel: "Journal Article",
    Journal: "Atmospheric Research",
    year: 2025,
    doi: "https://doi.org/10.1016/j.atmosres.2025.108531",
    featured: true,
  },
  {
    id: 3,
    title: "Development of a Virga Detection Tool and Associated Study of Arctic Virga and Precipitation",
    authors: "Saini, L., Das, S., Murukesh, N.",
    type: "journal",
    typeLabel: "Journal Article",
    Journal: "JGR: Atmosphere",
    year: 2026,
    doi: "https://doi.org/10.1029/2025JD044204",
    featured: true,
  },
  {
    id: 1,
    title: "Micro Rain Radar based Virga Detection Algorithm",
    authors: "Saini, L., Das, S., Murukesh, N.",
    type: "conference",
    typeLabel: "Conference Paper",
    Conference: "IGARSS 2025 - 2025 IEEE International Geoscience and Remote Sensing Symposium",
    Venue: "Brisbane, Australia",
    year: 2025,
    doi: "https://doi.org/10.1109/IGARSS55030.2025.11243520",
    featured: true,
  },
  {
    id: 2,
    title: "Virga Observation over NY- Ålesund, Arctic Using Micro Rain Radar",
    authors: "Saini, L., Das, S., Murukesh, N.",
    type: "conference",
    typeLabel: "Conference Paper",
    Conference: "IGARSS 2024 - 2024 IEEE International Geoscience and Remote Sensing Symposium",
    Venue: "Greece",
    year: 2024,
    doi: "https://doi.org/10.1109/IGARSS53475.2024.10642357",
    featured: true,
  },
  {
    id: 3,
    title: "An Investigation on Arctic Precipitation",
    authors: "Saini, L., Das, S., Murukesh, N.",
    type: "conference",
    typeLabel: "Conference Paper",
    Conference: "2022 URSI Regional Conference on Radio Science (USRI-RCRS)",
    Venue: "Indore, India",
    year: 2022,
    doi: "https://doi.org/10.23919/URSI-RCRS56822.2022.10118526",
    featured: true,
  },

  {
    id: 4,
    title: "Z-R Relationship and DSD Based on Precipitation Classification: An Arctic Study from Ny-Ålesund",
    authors: "Saini, L., Datta, S., Das, S., Murukesh, N.",
    type: "conference",
    typeLabel: "Conference Paper",
    Conference: "URSI General Assembly and Scientific Symposium",
    Venue: "Kyoto, Japan",
    year: 2023,
    doi: "https://doi.org/10.46620/URSIGASS.2023.3188.OJZR7254",
    featured: true,
  },

  {
    id: 5,
    title: "Investigation of Rain Virga in Arctic",
    authors: "Saini, L., Datta, S., Das, S., Murukesh, N.",
    type: "conference",
    typeLabel: "Conference Paper",
    Conference: "6th URSI Regional Conference on Radio Science",
    Venue: "Nainital, India",
    year: 2024,
    doi: "https://doi.org/10.46620/URSI_RSRC24/1214UIC7098",
    featured: true,
  },
  {
    id: 6,
    title: "Ground-Based Observations of an Unprecedented Rainfall Event Over Indore, India: A Multi-Instrument Approach",
    authors: "Singh, N., Tyagi, v., Saini, L., Das, S.",
    type: "conference",
    typeLabel: "Conference Paper",
    Conference: "IGARSS 2024 - 2024 IEEE International Geoscience and Remote Sensing Symposium",
    Venue: "Greece",
    year: 2024,
    doi: "https://doi.org/10.1109/IGARSS53475.2024.10642859",
    featured: true,
  },
  {
    id: 1,
    title: "Microphysical Study of Precipitation over Ny-Ålesund, an Arctic Location",
    authors: "Saini, L., Das, S., Murukesh, N.",
    type: "book_chapter",
    typeLabel: "Book Chapters",
    Book: "Radar Meteorology and its Applications (pp.103-110)",
    Publisher: "Springer Nature Singapore, Singapore",
    year: 2026,
    doi: "https://doi.org/10.1007/978-981-95-5409-6_8",
    featured: true,
  },


];
export const projects = [
  {
    id: 1,
    title: "Arctic Precipitation Microphysics Study",
    description: "Analysis of Arctic precipitation using radar and ground-based instruments.",
    shortDescription: "Arctic precipitation analysis",
    status: "ongoing",
    statusLabel: "Ongoing",
    technologies: ["Python", "MATLAB", "NetCDF"],
    featured: true,
  },
  {
    id: 2,
    title: "Virga Detection Algorithm",
    description: "Developed Micro Rain Radar-based algorithm for virga detection.",
    shortDescription: "Radar-based virga detection",
    status: "completed",
    statusLabel: "Completed",
    technologies: ["Python", "MATLAB"],
    featured: true,
  },
];
export const education = [
  {
    id: 1,
    degree: "PhD in Astronomy, Astrophysics and Space Engineering",
    institution: "Indian Institute of Technology Indore",
    yearStart: 2021,
    yearEnd: 2026,
    grade: "8.25 CGPA",
  },
  {
    id: 2,
    degree: "M.Sc. Physics",
    institution: "University of Delhi",
    yearStart: 2019,
    yearEnd: 2021,
    grade: "6.9 CGPA",
  },
  {
    id: 3,
    degree: "B.Sc. Mathematical Sciences",
    institution: "University of Rajasthan",
    yearStart: 2016,
    yearEnd: 2019,
    grade: "65.11%",
  },
];
export const experience = [
  {
    id: 1,
    title: "Doctoral Researcher (CSIR Fellow)",
    organization: "IIT Indore",
    type: "Research",
    startDate: "2021",
    endDate: "2026",
    isCurrent: false,
    location: "India",
    description: "Working on Arctic precipitation microphysics and atmospheric data analysis.",
  },
  {
    id: 2,
    title: "Teaching Assistant",
    organization: "IIT Indore",
    type: "Teaching",
    startDate: "2022",
    endDate: "2024",
    isCurrent: false,
    location: "India",
    description: "Assisting in remote sensing and GNSS courses.",
  },
  {
    id: 3,
    title: "Online Educator",
    organization: "Chegg / CourseHero / Bartleby",
    type: "Teaching",
    startDate: "2020",
    endDate: "2023",
    isCurrent: false,
    location: "Remote",
    description: "Provided academic guidance in geoscience and physics.",
  },
];
export const awards = [
  {
    id: 1,
    title: "IEEE GRSS Student Grand Challenge Winner",
    organization: "IEEE GRSS",
    year: 2025,
  },
  {
    id: 2,
    title: "International Travel Grant for IGARSS 2025 in Brisbane, Australia",
    organization: "IEEE GRSS",
    year: 2025,
  },
  {
    id: 3,
    title: "International Travel Scheme for Svalbard Science Conference 2025 in Oslo, Norway",
    organization: "ANRF",
    year: 2025,
  },
  {
    id: 4,
    title: "Bharatiya Antariksh Hackathon Winner",
    organization: "ISRO",
    year: 2024,
  },

  {
    id: 5,
    title: "Indian-Arctic Winter Expedition 2023-24 (Batch 03)",
    organization: "NCPOR, MoES, GOI",
    year: 2024,
  },
  {
    id: 6,
    title: "CSIR-NET JRF",
    organization: "CSIR India",
    year: 2019,
  },
];
